# runtime: python
# api_version: 1
# threadsafe: false

# handlers:
# - url: /
#   script: test.app


# runtime: python27
# threadsafe: true

# handlers:
# - url: /
#   script: test.app

runtime: python27
api_version: 1
threadsafe: true

handlers:
# - url: /static
#   static_dir: static

- url: /
  script: test.app

# - url: /(.*)
#   static_files: www/\1
#   upload: www/(.*)